const categories = [
  { id: 1, name: 'Groceries' },
  { id: 2, name: 'Clothing' },
  { id: 3, name: 'Electronics' },
  { id: 4, name: 'Home Decor' },
  { id: 5, name: 'Toys' },
  { id: 6, name: 'Beauty' },
  { id: 7, name: 'Sporting Goods' },
  { id: 8, name: 'Office Supplies' },
  { id: 9, name: 'Books' },
  { id: 10, name: 'Pet Supplies' },
  { id: 11, name: 'Tools' },
  { id: 12, name: 'Automotive' },
  { id: 13, name: 'Baby' },
  { id: 14, name: 'Music' },
  { id: 15, name: 'Movies' },
  { id: 16, name: 'Jewelry' },
  { id: 17, name: 'Shoes' },
  { id: 18, name: 'Accessories' },
  { id: 19, name: 'Food' },
  { id: 20, name: 'Kitchen' },
  { id: 21, name: 'Health' },
  { id: 22, name: 'Outdoor' },
  { id: 23, name: 'Travel' },
  { id: 24, name: 'School Supplies' },
  { id: 25, name: 'Art Supplies' },
  { id: 26, name: 'Crafts' },
  { id: 27, name: 'Garden' },
  { id: 28, name: 'Party Supplies' },
  { id: 29, name: 'Fitness' },
];

export default categories;
